name: Build & Push Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_API: ghcr.io/${{ github.repository_owner }}/cashquest-api
  IMAGE_WEB: ghcr.io/${{ github.repository_owner }}/cashquest-web

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # API (Nest)
      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/api-nest.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

      # Flutter Web (nginx)
      - name: Build & Push Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/web-flutter.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}
